### ISSUE TITLE
133 labels in OASIS and CANDI datasets

### ISSUE THREAD

**Issue by CRazorback** [MASILab/UNesT#1]
Thank you for sharing your great work.

According to the manuscript, the training and testing images were manually traced to 133 labels based on BrainCOLOR protocol. Are these labels publicly available or created in-house? If the latter, could you kindly share them for reproduction and comparison?

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
